[project]
name = "moneyflow"
version = "1.0.0"
description = "Aplicación de gestión de gastos personales"
dependencies = [
    "flet"
]

[tool.flet]
org = "com.moneyflow"
product = "MoneyFlow"

[tool.flet.app]
path = "src"

[tool.flet.android]
app_name = "MoneyFlow"
package_name = "com.moneyflow.app"
icon = "assets/icon.png"

[tool.flet.windows]
icon = "assets/icon.png"