name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Flet y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install flet[all]
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Instalar Flet y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install flet[all]
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Compilar APK
        run: |
          # Usamos echo "y" para responder automáticamente a la instalación de Flutter SDK si Flet lo solicita
          echo "y" | flet build apk --output build

      - name: Subir APK terminada
        uses: actions/upload-artifact@v4
        with:
          name: MoneyFlow-APK
          path: build/apk/*.apk

      - name: Subir APK terminada
        uses: actions/upload-artifact@v4
        with:
          name: MoneyFlow-APK
          path: build/apk/*.apk